POST http://localhost:8080/users
Content-Type: application/json

{
    "name":"Natalino",
    "password":"123"
}

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
    "name":"Natalino",
    "password":"123"
}

###

post http://localhost:8080/refresh/

###